SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_CENTER = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)

UPDATES_PER_SECOND = 60
SECONDS_PER_UPDATE = 1.0 / UPDATES_PER_SECOND

MAX_RENDERS_PER_SECOND = 100
MIN_SECONDS_PER_RENDER = 1.0 / MAX_RENDERS_PER_SECOND

CONSOLE_MAX_LINES = 8

SCALE_FACTOR = 3    # 16x16 * 3 == 48x48

PLAYER_SPEED = 200  # pixels per second