import json

import pygame

from config import *


def load_character_anim_data():
    ''' Parses the json data generated by aseprite and returns a dict of 
        animations with lists of frames (surfaces) loaded from the spritesheet.
    '''
    spritesheet = pygame.image.load('data/character_anim.png').convert_alpha()
    gfx_data = {}  # keys = anim name, values = lists of pygame.Surface() objs

    with open('data/character_anim.json') as infile:
        json_data = json.load(infile)
        for key in json_data['frames'].keys():
            anim_name = ''  # key for anim_dict
            i = 0
            while key[i].isalpha():
                anim_name += key[i]
                i += 1

            if anim_name not in gfx_data:
                gfx_data[anim_name] = []
            
            frame_size = (json_data['frames'][key]['sourceSize']['w'],
                          json_data['frames'][key]['sourceSize']['h'])
            frame = pygame.Surface(frame_size)
            frame.set_colorkey((0,0,0))
            frame_data = json_data['frames'][key]['frame']
            area = (frame_data['x'], frame_data['y'],
                    frame_data['w'], frame_data['h'])
            frame.blit(spritesheet, (0,0), area)
            frame = pygame.transform.scale_by(frame, SCALE_FACTOR)
            gfx_data[anim_name].append(frame)

    for key, value in gfx_data.items():
        print(key + ', ' + str(len(value)))
    
    return gfx_data


SIZE = 24  # tile size, anim frames are 24x24

def load_frame(source, area):
    frame = pygame.Surface((SIZE,SIZE))
    frame.set_colorkey((0,0,0))
    frame.blit(source, (0,0), area)
    frame = pygame.transform.scale_by(frame, SCALE_FACTOR)
    return frame

def load_character_spritesheet():
    spritesheet = pygame.image.load('data/walk and idle.png').convert_alpha()
    anim_dict = {'idle_left': [],
                 'idle_right': [],
                 'walk_left': [],
                 'walk_right': [] }  # TODO: Make values lists of frame surfaces.

    # load idle animations
    for i in range(4):
        frame_rect = pygame.Rect((SIZE * i, 0), (SIZE,SIZE))
        frame = load_frame(spritesheet, frame_rect)
        if i < 2:
            anim_dict['idle_left'].append(frame)
        else:
            anim_dict['idle_right'].append(frame)
    
    # load walk animations
    for i in range(8):
        frame_rect = pygame.Rect((SIZE * i, SIZE), (SIZE,SIZE))
        frame = load_frame(spritesheet, frame_rect)
        anim_dict['walk_left'].append(frame)

        frame_rect = pygame.Rect((SIZE * i, SIZE * 2), (SIZE,SIZE))
        frame = load_frame(spritesheet, frame_rect)
        anim_dict['walk_right'].append(frame)
    
    return anim_dict
